### ISSUE TITLE
Release v0.1.3

### ISSUE THREAD

**Issue by jwnimmer-tri** [oxfordcontrol/qdldl#17]
Hello everyone.  It looks like there was a 0.1.3 release, but https://github.com/oxfordcontrol/qdldl/releases doesn't show it.  I think that's because it was created using a branch https://github.com/oxfordcontrol/qdldl/tree/release-0.1.3 instead of a tag https://github.com/oxfordcontrol/qdldl/tags.

I'm able to work around it by using pin to b145d782e88cc2308c54bf0c9f221d9f6597082c on master, but I thought I'd post in case you'd want to tidy it up.

**Comment by bstellato** [comment]
Oooops thanks for pointing this out! I cannot believe I forgot to do so.
I just tagged that commit and created a release: https://github.com/oxfordcontrol/qdldl/releases/tag/v0.1.3

**Comment by jwnimmer-tri** [comment]
Looks great, thanks!
