### ISSUE TITLE
compile error issue

### ISSUE THREAD

**Issue by NUDTUGVexplorer** [oxfordcontrol/qdldl#29]
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ugv/software/osqp-eigen-master/build
ugv@ugv-ThinkPad-S2:~/software/osqp-eigen-master/build$ make -j8
Scanning dependencies of target OsqpEigen
[ 25%] Building CXX object CMakeFiles/OsqpEigen.dir/src/Solver.cpp.o
[ 50%] Building CXX object CMakeFiles/OsqpEigen.dir/src/Settings.cpp.o
[ 75%] Building CXX object CMakeFiles/OsqpEigen.dir/src/Data.cpp.o
/home/ugv/software/osqp-eigen-master/src/Solver.cpp: In constructor ‘OsqpEigen::Solver::Solver()’:
/home/ugv/software/osqp-eigen-master/src/Solver.cpp:16:18: error: ‘make_unique’ is not a member of ‘std’
     m_settings = std::make_unique<OsqpEigen::Settings>();
                  ^
/home/ugv/software/osqp-eigen-master/src/Solver.cpp:16:54: error: expected primary-expression before ‘>’ token
     m_settings = std::make_unique<OsqpEigen::Settings>();
                                                      ^
/home/ugv/software/osqp-eigen-master/src/Solver.cpp:16:56: error: expected primary-expression before ‘)’ token
     m_settings = std::make_unique<OsqpEigen::Settings>();
                                                        ^
/home/ugv/software/osqp-eigen-master/src/Solver.cpp:17:14: error: ‘make_unique’ is not a member of ‘std’
     m_data = std::make_unique<OsqpEigen::Data>();
              ^
/home/ugv/software/osqp-eigen-master/src/Solver.cpp:17:46: error: expected primary-expression before ‘>’ token
     m_data = std::make_unique<OsqpEigen::Data>();
                                              ^
/home/ugv/software/osqp-eigen-master/src/Solver.cpp:17:48: error: expected primary-expression before ‘)’ token
     m_data = std::make_unique<OsqpEigen::Data>();
                                                ^
make[2]: *** [CMakeFiles/OsqpEigen.dir/src/Solver.cpp.o] Error 1
make[1]: *** [CMakeFiles/OsqpEigen.dir/all] Error 2
make: *** [all] Error 2

**Comment by bstellato** [comment]
Looks like it was a GCC problem when compiling with `osqp-eigen` resolved in https://github.com/robotology/osqp-eigen/issues/53 I am going to close this issue. Feel free to reopen it if you need.
