### ISSUE TITLE
[openSUSE] How to move file from /usr/lib/ to /usr/lib64?

### ISSUE THREAD

**Issue by kevinsmia1939** [oxfordcontrol/qdldl#32]
Hello,
I'm trying to package qdldl to openSUSE Linux.
I found a files that went into /usr/lib as shown below.
I think that if I build for 64-bit, it should go to /usr/lib64.
Are there cmake flag I can add to make it go to /usr/lib64?

Thanks.

```
/usr/lib/cmake/qdldl/qdldl-config.cmake
/usr/lib/cmake/qdldl/qdldl-targets-relwithdebinfo.cmake
/usr/lib/cmake/qdldl/qdldl-targets.cmake
```

**Comment by imciner2** [comment]
Unfortunately it will require a patch to the CMake to get them installed properly without any copying, you can see the change needed here: https://github.com/oxfordcontrol/qdldl/pull/33/files#diff-af3b638bc2a3e6c650974192a53c7291R183. Alternatively, you could just copy them after installing inside the `%install` section of the spec file until #33 is merged and a new version is released.

**Comment by kevinsmia1939** [comment]
> Unfortunately it will require a patch to the CMake to get them installed properly without any copying, you can see the change needed here: https://github.com/oxfordcontrol/qdldl/pull/33/files#diff-af3b638bc2a3e6c650974192a53c7291R183. Alternatively, you could just copy them after installing inside the `%install` section of the spec file until #33 is merged and a new version is released.

Got it, will wait for new version. thanks.
