### ISSUE TITLE
library output names

### ISSUE THREAD

**Issue by mlubin** [oxfordcontrol/qdldl#4]
The name `libqdldlstatic` is a bit unusual. Why not output both `libqdldl.(dynamic library extension)` and `libqdldl.(static library extension)`? E.g., on linux `libqdldl.so` and `libqdldl.a`.

**Comment by bstellato** [comment]
Good idea. I have enforced the same name in this commit: 6f6b2bb578ffead48e6ad5a6bb8b2fe5c2469492.
